//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace BeSmartMRP.Report.LocalDataSet {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DTSPSTMOVE")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DTSPSTMOVE : global::System.Data.DataSet {
        
        private XRPSTMOVEDataTable tableXRPSTMOVE;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public DTSPSTMOVE() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected DTSPSTMOVE(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["XRPSTMOVE"] != null)) {
                    base.Tables.Add(new XRPSTMOVEDataTable(ds.Tables["XRPSTMOVE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public XRPSTMOVEDataTable XRPSTMOVE {
            get {
                return this.tableXRPSTMOVE;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DTSPSTMOVE cln = ((DTSPSTMOVE)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["XRPSTMOVE"] != null)) {
                    base.Tables.Add(new XRPSTMOVEDataTable(ds.Tables["XRPSTMOVE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableXRPSTMOVE = ((XRPSTMOVEDataTable)(base.Tables["XRPSTMOVE"]));
            if ((initTable == true)) {
                if ((this.tableXRPSTMOVE != null)) {
                    this.tableXRPSTMOVE.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DTSPSTMOVE";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DTSPSTMOVE.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableXRPSTMOVE = new XRPSTMOVEDataTable();
            base.Tables.Add(this.tableXRPSTMOVE);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializeXRPSTMOVE() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DTSPSTMOVE ds = new DTSPSTMOVE();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void XRPSTMOVERowChangeEventHandler(object sender, XRPSTMOVERowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class XRPSTMOVEDataTable : global::System.Data.TypedTableBase<XRPSTMOVERow> {
            
            private global::System.Data.DataColumn columncQcCrGrp;
            
            private global::System.Data.DataColumn columncQnCrGrp;
            
            private global::System.Data.DataColumn columncQcPdGrp;
            
            private global::System.Data.DataColumn columncQnPdGrp;
            
            private global::System.Data.DataColumn columncQcPdType;
            
            private global::System.Data.DataColumn columncQnPdType;
            
            private global::System.Data.DataColumn columncQcProd;
            
            private global::System.Data.DataColumn columncQnProd;
            
            private global::System.Data.DataColumn columnnStdPrice;
            
            private global::System.Data.DataColumn columncQcUM;
            
            private global::System.Data.DataColumn columncQnUM;
            
            private global::System.Data.DataColumn columnnBFQty;
            
            private global::System.Data.DataColumn columnnBFAmt;
            
            private global::System.Data.DataColumn columnnQty_IN;
            
            private global::System.Data.DataColumn columnnQty_Out;
            
            private global::System.Data.DataColumn columnnQty_Ret;
            
            private global::System.Data.DataColumn columnnAmt_IN;
            
            private global::System.Data.DataColumn columnnAmt_Out;
            
            private global::System.Data.DataColumn columnnAmt_Ret;
            
            private global::System.Data.DataColumn columncCtrlStock;
            
            private global::System.Data.DataColumn columncQcAcChart;
            
            private global::System.Data.DataColumn columncQnAcChart;
            
            private global::System.Data.DataColumn columncQcAcChart2;
            
            private global::System.Data.DataColumn columncQnAcChart2;
            
            private global::System.Data.DataColumn columnnQty;
            
            private global::System.Data.DataColumn columnnSaleQty;
            
            private global::System.Data.DataColumn columncRemark;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public XRPSTMOVEDataTable() {
                this.TableName = "XRPSTMOVE";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal XRPSTMOVEDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected XRPSTMOVEDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQcCrGrpColumn {
                get {
                    return this.columncQcCrGrp;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQnCrGrpColumn {
                get {
                    return this.columncQnCrGrp;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQcPdGrpColumn {
                get {
                    return this.columncQcPdGrp;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQnPdGrpColumn {
                get {
                    return this.columncQnPdGrp;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQcPdTypeColumn {
                get {
                    return this.columncQcPdType;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQnPdTypeColumn {
                get {
                    return this.columncQnPdType;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQcProdColumn {
                get {
                    return this.columncQcProd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQnProdColumn {
                get {
                    return this.columncQnProd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nStdPriceColumn {
                get {
                    return this.columnnStdPrice;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQcUMColumn {
                get {
                    return this.columncQcUM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQnUMColumn {
                get {
                    return this.columncQnUM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nBFQtyColumn {
                get {
                    return this.columnnBFQty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nBFAmtColumn {
                get {
                    return this.columnnBFAmt;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nQty_INColumn {
                get {
                    return this.columnnQty_IN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nQty_OutColumn {
                get {
                    return this.columnnQty_Out;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nQty_RetColumn {
                get {
                    return this.columnnQty_Ret;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nAmt_INColumn {
                get {
                    return this.columnnAmt_IN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nAmt_OutColumn {
                get {
                    return this.columnnAmt_Out;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nAmt_RetColumn {
                get {
                    return this.columnnAmt_Ret;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cCtrlStockColumn {
                get {
                    return this.columncCtrlStock;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQcAcChartColumn {
                get {
                    return this.columncQcAcChart;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQnAcChartColumn {
                get {
                    return this.columncQnAcChart;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQcAcChart2Column {
                get {
                    return this.columncQcAcChart2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cQnAcChart2Column {
                get {
                    return this.columncQnAcChart2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nQtyColumn {
                get {
                    return this.columnnQty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn nSaleQtyColumn {
                get {
                    return this.columnnSaleQty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn cRemarkColumn {
                get {
                    return this.columncRemark;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public XRPSTMOVERow this[int index] {
                get {
                    return ((XRPSTMOVERow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event XRPSTMOVERowChangeEventHandler XRPSTMOVERowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event XRPSTMOVERowChangeEventHandler XRPSTMOVERowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event XRPSTMOVERowChangeEventHandler XRPSTMOVERowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event XRPSTMOVERowChangeEventHandler XRPSTMOVERowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddXRPSTMOVERow(XRPSTMOVERow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public XRPSTMOVERow AddXRPSTMOVERow(
                        string cQcCrGrp, 
                        string cQnCrGrp, 
                        string cQcPdGrp, 
                        string cQnPdGrp, 
                        string cQcPdType, 
                        string cQnPdType, 
                        string cQcProd, 
                        string cQnProd, 
                        decimal nStdPrice, 
                        string cQcUM, 
                        string cQnUM, 
                        decimal nBFQty, 
                        decimal nBFAmt, 
                        decimal nQty_IN, 
                        decimal nQty_Out, 
                        decimal nQty_Ret, 
                        decimal nAmt_IN, 
                        decimal nAmt_Out, 
                        decimal nAmt_Ret, 
                        string cCtrlStock, 
                        string cQcAcChart, 
                        string cQnAcChart, 
                        string cQcAcChart2, 
                        string cQnAcChart2, 
                        decimal nQty, 
                        decimal nSaleQty, 
                        string cRemark) {
                XRPSTMOVERow rowXRPSTMOVERow = ((XRPSTMOVERow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        cQcCrGrp,
                        cQnCrGrp,
                        cQcPdGrp,
                        cQnPdGrp,
                        cQcPdType,
                        cQnPdType,
                        cQcProd,
                        cQnProd,
                        nStdPrice,
                        cQcUM,
                        cQnUM,
                        nBFQty,
                        nBFAmt,
                        nQty_IN,
                        nQty_Out,
                        nQty_Ret,
                        nAmt_IN,
                        nAmt_Out,
                        nAmt_Ret,
                        cCtrlStock,
                        cQcAcChart,
                        cQnAcChart,
                        cQcAcChart2,
                        cQnAcChart2,
                        nQty,
                        nSaleQty,
                        cRemark};
                rowXRPSTMOVERow.ItemArray = columnValuesArray;
                this.Rows.Add(rowXRPSTMOVERow);
                return rowXRPSTMOVERow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                XRPSTMOVEDataTable cln = ((XRPSTMOVEDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new XRPSTMOVEDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columncQcCrGrp = base.Columns["cQcCrGrp"];
                this.columncQnCrGrp = base.Columns["cQnCrGrp"];
                this.columncQcPdGrp = base.Columns["cQcPdGrp"];
                this.columncQnPdGrp = base.Columns["cQnPdGrp"];
                this.columncQcPdType = base.Columns["cQcPdType"];
                this.columncQnPdType = base.Columns["cQnPdType"];
                this.columncQcProd = base.Columns["cQcProd"];
                this.columncQnProd = base.Columns["cQnProd"];
                this.columnnStdPrice = base.Columns["nStdPrice"];
                this.columncQcUM = base.Columns["cQcUM"];
                this.columncQnUM = base.Columns["cQnUM"];
                this.columnnBFQty = base.Columns["nBFQty"];
                this.columnnBFAmt = base.Columns["nBFAmt"];
                this.columnnQty_IN = base.Columns["nQty_IN"];
                this.columnnQty_Out = base.Columns["nQty_Out"];
                this.columnnQty_Ret = base.Columns["nQty_Ret"];
                this.columnnAmt_IN = base.Columns["nAmt_IN"];
                this.columnnAmt_Out = base.Columns["nAmt_Out"];
                this.columnnAmt_Ret = base.Columns["nAmt_Ret"];
                this.columncCtrlStock = base.Columns["cCtrlStock"];
                this.columncQcAcChart = base.Columns["cQcAcChart"];
                this.columncQnAcChart = base.Columns["cQnAcChart"];
                this.columncQcAcChart2 = base.Columns["cQcAcChart2"];
                this.columncQnAcChart2 = base.Columns["cQnAcChart2"];
                this.columnnQty = base.Columns["nQty"];
                this.columnnSaleQty = base.Columns["nSaleQty"];
                this.columncRemark = base.Columns["cRemark"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columncQcCrGrp = new global::System.Data.DataColumn("cQcCrGrp", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQcCrGrp);
                this.columncQnCrGrp = new global::System.Data.DataColumn("cQnCrGrp", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQnCrGrp);
                this.columncQcPdGrp = new global::System.Data.DataColumn("cQcPdGrp", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQcPdGrp);
                this.columncQnPdGrp = new global::System.Data.DataColumn("cQnPdGrp", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQnPdGrp);
                this.columncQcPdType = new global::System.Data.DataColumn("cQcPdType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQcPdType);
                this.columncQnPdType = new global::System.Data.DataColumn("cQnPdType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQnPdType);
                this.columncQcProd = new global::System.Data.DataColumn("cQcProd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQcProd);
                this.columncQnProd = new global::System.Data.DataColumn("cQnProd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQnProd);
                this.columnnStdPrice = new global::System.Data.DataColumn("nStdPrice", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnStdPrice);
                this.columncQcUM = new global::System.Data.DataColumn("cQcUM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQcUM);
                this.columncQnUM = new global::System.Data.DataColumn("cQnUM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQnUM);
                this.columnnBFQty = new global::System.Data.DataColumn("nBFQty", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnBFQty);
                this.columnnBFAmt = new global::System.Data.DataColumn("nBFAmt", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnBFAmt);
                this.columnnQty_IN = new global::System.Data.DataColumn("nQty_IN", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnQty_IN);
                this.columnnQty_Out = new global::System.Data.DataColumn("nQty_Out", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnQty_Out);
                this.columnnQty_Ret = new global::System.Data.DataColumn("nQty_Ret", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnQty_Ret);
                this.columnnAmt_IN = new global::System.Data.DataColumn("nAmt_IN", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnAmt_IN);
                this.columnnAmt_Out = new global::System.Data.DataColumn("nAmt_Out", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnAmt_Out);
                this.columnnAmt_Ret = new global::System.Data.DataColumn("nAmt_Ret", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnAmt_Ret);
                this.columncCtrlStock = new global::System.Data.DataColumn("cCtrlStock", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncCtrlStock);
                this.columncQcAcChart = new global::System.Data.DataColumn("cQcAcChart", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQcAcChart);
                this.columncQnAcChart = new global::System.Data.DataColumn("cQnAcChart", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQnAcChart);
                this.columncQcAcChart2 = new global::System.Data.DataColumn("cQcAcChart2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQcAcChart2);
                this.columncQnAcChart2 = new global::System.Data.DataColumn("cQnAcChart2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncQnAcChart2);
                this.columnnQty = new global::System.Data.DataColumn("nQty", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnQty);
                this.columnnSaleQty = new global::System.Data.DataColumn("nSaleQty", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnSaleQty);
                this.columncRemark = new global::System.Data.DataColumn("cRemark", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncRemark);
                this.columncQcCrGrp.Caption = "cName2";
                this.columncQnCrGrp.Caption = "cCateg";
                this.columncQcPdGrp.Caption = "cGroup";
                this.columncQnPdGrp.Caption = "cQcAcChart";
                this.columncQcPdType.Caption = "cQnAcChart";
                this.columnnStdPrice.DefaultValue = ((decimal)(0m));
                this.columnnBFAmt.Caption = "cVatIsOut";
                this.columnnQty.DefaultValue = ((decimal)(0m));
                this.columnnSaleQty.DefaultValue = ((decimal)(0m));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public XRPSTMOVERow NewXRPSTMOVERow() {
                return ((XRPSTMOVERow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new XRPSTMOVERow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(XRPSTMOVERow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.XRPSTMOVERowChanged != null)) {
                    this.XRPSTMOVERowChanged(this, new XRPSTMOVERowChangeEvent(((XRPSTMOVERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.XRPSTMOVERowChanging != null)) {
                    this.XRPSTMOVERowChanging(this, new XRPSTMOVERowChangeEvent(((XRPSTMOVERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.XRPSTMOVERowDeleted != null)) {
                    this.XRPSTMOVERowDeleted(this, new XRPSTMOVERowChangeEvent(((XRPSTMOVERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.XRPSTMOVERowDeleting != null)) {
                    this.XRPSTMOVERowDeleting(this, new XRPSTMOVERowChangeEvent(((XRPSTMOVERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemoveXRPSTMOVERow(XRPSTMOVERow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DTSPSTMOVE ds = new DTSPSTMOVE();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "XRPSTMOVEDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class XRPSTMOVERow : global::System.Data.DataRow {
            
            private XRPSTMOVEDataTable tableXRPSTMOVE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal XRPSTMOVERow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableXRPSTMOVE = ((XRPSTMOVEDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQcCrGrp {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQcCrGrpColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQcCrGrp\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQcCrGrpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQnCrGrp {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQnCrGrpColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQnCrGrp\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQnCrGrpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQcPdGrp {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQcPdGrpColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQcPdGrp\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQcPdGrpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQnPdGrp {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQnPdGrpColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQnPdGrp\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQnPdGrpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQcPdType {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQcPdTypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQcPdType\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQcPdTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQnPdType {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQnPdTypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQnPdType\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQnPdTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQcProd {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQcProdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQcProd\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQcProdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQnProd {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQnProdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQnProd\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQnProdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nStdPrice {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nStdPriceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nStdPrice\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nStdPriceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQcUM {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQcUMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQcUM\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQcUMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQnUM {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQnUMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQnUM\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQnUMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nBFQty {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nBFQtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nBFQty\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nBFQtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nBFAmt {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nBFAmtColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nBFAmt\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nBFAmtColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nQty_IN {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nQty_INColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nQty_IN\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nQty_INColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nQty_Out {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nQty_OutColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nQty_Out\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nQty_OutColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nQty_Ret {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nQty_RetColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nQty_Ret\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nQty_RetColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nAmt_IN {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nAmt_INColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nAmt_IN\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nAmt_INColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nAmt_Out {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nAmt_OutColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nAmt_Out\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nAmt_OutColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nAmt_Ret {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nAmt_RetColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nAmt_Ret\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nAmt_RetColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cCtrlStock {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cCtrlStockColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cCtrlStock\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cCtrlStockColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQcAcChart {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQcAcChartColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQcAcChart\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQcAcChartColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQnAcChart {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQnAcChartColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQnAcChart\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQnAcChartColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQcAcChart2 {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQcAcChart2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQcAcChart2\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQcAcChart2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cQnAcChart2 {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cQnAcChart2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cQnAcChart2\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cQnAcChart2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nQty {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nQtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nQty\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nQtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal nSaleQty {
                get {
                    try {
                        return ((decimal)(this[this.tableXRPSTMOVE.nSaleQtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nSaleQty\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.nSaleQtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string cRemark {
                get {
                    try {
                        return ((string)(this[this.tableXRPSTMOVE.cRemarkColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cRemark\' in table \'XRPSTMOVE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableXRPSTMOVE.cRemarkColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQcCrGrpNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQcCrGrpColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQcCrGrpNull() {
                this[this.tableXRPSTMOVE.cQcCrGrpColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQnCrGrpNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQnCrGrpColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQnCrGrpNull() {
                this[this.tableXRPSTMOVE.cQnCrGrpColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQcPdGrpNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQcPdGrpColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQcPdGrpNull() {
                this[this.tableXRPSTMOVE.cQcPdGrpColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQnPdGrpNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQnPdGrpColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQnPdGrpNull() {
                this[this.tableXRPSTMOVE.cQnPdGrpColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQcPdTypeNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQcPdTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQcPdTypeNull() {
                this[this.tableXRPSTMOVE.cQcPdTypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQnPdTypeNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQnPdTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQnPdTypeNull() {
                this[this.tableXRPSTMOVE.cQnPdTypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQcProdNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQcProdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQcProdNull() {
                this[this.tableXRPSTMOVE.cQcProdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQnProdNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQnProdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQnProdNull() {
                this[this.tableXRPSTMOVE.cQnProdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnStdPriceNull() {
                return this.IsNull(this.tableXRPSTMOVE.nStdPriceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnStdPriceNull() {
                this[this.tableXRPSTMOVE.nStdPriceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQcUMNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQcUMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQcUMNull() {
                this[this.tableXRPSTMOVE.cQcUMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQnUMNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQnUMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQnUMNull() {
                this[this.tableXRPSTMOVE.cQnUMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnBFQtyNull() {
                return this.IsNull(this.tableXRPSTMOVE.nBFQtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnBFQtyNull() {
                this[this.tableXRPSTMOVE.nBFQtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnBFAmtNull() {
                return this.IsNull(this.tableXRPSTMOVE.nBFAmtColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnBFAmtNull() {
                this[this.tableXRPSTMOVE.nBFAmtColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnQty_INNull() {
                return this.IsNull(this.tableXRPSTMOVE.nQty_INColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnQty_INNull() {
                this[this.tableXRPSTMOVE.nQty_INColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnQty_OutNull() {
                return this.IsNull(this.tableXRPSTMOVE.nQty_OutColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnQty_OutNull() {
                this[this.tableXRPSTMOVE.nQty_OutColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnQty_RetNull() {
                return this.IsNull(this.tableXRPSTMOVE.nQty_RetColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnQty_RetNull() {
                this[this.tableXRPSTMOVE.nQty_RetColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnAmt_INNull() {
                return this.IsNull(this.tableXRPSTMOVE.nAmt_INColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnAmt_INNull() {
                this[this.tableXRPSTMOVE.nAmt_INColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnAmt_OutNull() {
                return this.IsNull(this.tableXRPSTMOVE.nAmt_OutColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnAmt_OutNull() {
                this[this.tableXRPSTMOVE.nAmt_OutColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnAmt_RetNull() {
                return this.IsNull(this.tableXRPSTMOVE.nAmt_RetColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnAmt_RetNull() {
                this[this.tableXRPSTMOVE.nAmt_RetColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscCtrlStockNull() {
                return this.IsNull(this.tableXRPSTMOVE.cCtrlStockColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcCtrlStockNull() {
                this[this.tableXRPSTMOVE.cCtrlStockColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQcAcChartNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQcAcChartColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQcAcChartNull() {
                this[this.tableXRPSTMOVE.cQcAcChartColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQnAcChartNull() {
                return this.IsNull(this.tableXRPSTMOVE.cQnAcChartColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQnAcChartNull() {
                this[this.tableXRPSTMOVE.cQnAcChartColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQcAcChart2Null() {
                return this.IsNull(this.tableXRPSTMOVE.cQcAcChart2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQcAcChart2Null() {
                this[this.tableXRPSTMOVE.cQcAcChart2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscQnAcChart2Null() {
                return this.IsNull(this.tableXRPSTMOVE.cQnAcChart2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcQnAcChart2Null() {
                this[this.tableXRPSTMOVE.cQnAcChart2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnQtyNull() {
                return this.IsNull(this.tableXRPSTMOVE.nQtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnQtyNull() {
                this[this.tableXRPSTMOVE.nQtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsnSaleQtyNull() {
                return this.IsNull(this.tableXRPSTMOVE.nSaleQtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetnSaleQtyNull() {
                this[this.tableXRPSTMOVE.nSaleQtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IscRemarkNull() {
                return this.IsNull(this.tableXRPSTMOVE.cRemarkColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetcRemarkNull() {
                this[this.tableXRPSTMOVE.cRemarkColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class XRPSTMOVERowChangeEvent : global::System.EventArgs {
            
            private XRPSTMOVERow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public XRPSTMOVERowChangeEvent(XRPSTMOVERow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public XRPSTMOVERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591